<?php declare(strict_types=1);
/**
 * Copyright © W. Poortman - Magewire 2021-present.
 *
 * Please read the README and LICENSE files for more
 * details on copyrights and license information.
 */

/** @var Magewire $magewireScripts */
/** @var Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */

use Magento\Framework\Escaper;
use Magewirephp\Magewire\ViewModel\Magewire;

$magewireScripts = $block->getData('viewModel');
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magewirephp_MagewireBackend/js/magewire": {
            "app_url": "<?= $escaper->escapeUrl($magewireScripts->getApplicationUrl()) ?>",
            "app_debug": <?= $escaper->escapeJs($magewireScripts->isDeveloperMode() ? 'true' : 'false') ?>
        }
    }
}
</script>
